### ISSUE TITLE
Relation to EasyMDE

### ISSUE THREAD

**Issue by marekdedic** [Inscryb/inscryb-markdown-editor#38]
Hi, I've been looking for a (maintained) replacement to SimpleMDE and found this and [EasyMDE](https://github.com/Ionaru/easy-markdown-editor) - what is the relation between the forks? I would really like to have my cake and eat it all :D

**Comment by GenaBitu** [comment]
Related issue: Ionaru/easy-markdown-editor#36

**Comment by CWharton** [comment]
I am aware of easy-markdown-editor, they are just another fork of SimpleMDE as are we. I started this editor because we use it within our company and talking with the founder of SimpleMDE he had no plans to maintain his version anymore. At the time we could not find another maintainer of the project so we started our own fork. We are open to PR to make this editor usable for you as well and we will update dependencies to keep the editor usable.
